import type {
  DraftRecord,
} from './types'


export function createSampleDraft(): DraftRecord {
  return {
    patient: {
      _tempId: 'patient-1',
      nhsNumber: '9990000018',
      nhsNumberVerified: true,
      prefix: 'Mrs',
      givenName: 'Sarah Jane',
      familyName: 'Thompson',
      dateOfBirth: '1965-03-14',
      gender: 'female',
      isActive: true,
      registrationType: 'Regular',
      registrationStart: '2010-04-01',
      address: '14 Wellbrook Avenue, Leeds, LS7 3PQ',
      phone: '0113 2468101',
    },
    organisation: {
      _tempId: 'org-1',
      name: 'The Wellbrook Surgery',
      odsCode: 'A81001',
      phone: '0113 2468100',
      address: '1 Wellbrook Parade, Leeds, LS7 3PQ',
    },
    organisations: [],
    practitioners: [
      {
        _tempId: 'prac-1',
        prefix: 'Dr',
        givenName: 'Jonathan',
        familyName: 'Clarke',
        sdsUserId: 'G8134455',
        sdsRoleProfileId: 'R8134455',
        gender: 'male',
      },
      {
        _tempId: 'prac-2',
        prefix: 'Dr',
        givenName: 'Amelia',
        familyName: 'Osei',
        sdsUserId: 'G8144566',
        sdsRoleProfileId: 'R8144566',
        gender: 'female',
      },
      {
        _tempId: 'prac-3',
        prefix: '',
        givenName: 'Helen',
        familyName: 'Griffiths',
        sdsUserId: 'G8154677',
        sdsRoleProfileId: 'R8154677',
        gender: 'female',
      },
    ],
    locations: [
      {
        _tempId: 'loc-1',
        name: 'Wellbrook Surgery — Main Building',
        address: '1 Wellbrook Parade, Leeds, LS7 3PQ',
      },
    ],
    medications: [],
    allergies: [],
    problems: [],
    consultations: [],
    immunisations: [],
    investigations: [],
    referrals: [],
    diaryEntries: [],
    codedData: [],
    documents: [],
  }
}

export function createFullSampleDraft(): DraftRecord {
  const base = createSampleDraft()
  return {
    ...base,
    medications: [{
      _tempId: 'med-1',
      drugName: 'Atorvastatin 20mg tablets',
      snomedCode: '325278007',
      prescriptionType: 'repeat',
      status: 'active',
      dose: '20 mg',
      frequency: 'Once a day',
      route: 'Oral',
      dosageInstruction: '1 tablet once daily at night',
      prescribedQuantityValue: 28,
      prescribedQuantityUnit: 'tablet',
      numberOfRepeatsAllowed: 6,
      startDate: '2022-01-15',
      prescriberTempId: 'prac-1',
      recorderTempId: 'prac-1',
      issues: [],
    }],
    allergies: [{
      _tempId: 'allergy-1',
      causativeAgent: 'Penicillin',
      snomedCode: '372687004',
      category: 'medication',
      criticality: 'high',
      reaction: 'Anaphylaxis',
      status: 'active',
      assertedDate: '2019-06-10',
      recorderTempId: 'prac-2',
      notes: [],
    }],
    problems: [{
      _tempId: 'prob-1',
      problem: 'Hypertension',
      snomedCode: '38341003',
      clinicalStatus: 'active',
      significance: 'major',
      startDate: '2018-03-22',
      asserterTempId: 'prac-1',
      notes: [],
    }],
    consultations: [{
      _tempId: 'cons-1',
      date: '2024-02-14',
      typeDisplay: 'Telephone consultation',
      clinicianTempId: 'prac-1',
      orgTempId: 'org-1',
      encounterClass: 'AMB',
      topics: [{
        _tempId: 'topic-1',
        title: 'Hypertension review',
        categories: [{
          _tempId: 'cat-1',
          title: 'History',
          items: [{
            _tempId: 'item-1',
            itemType: 'note',
            narrativeText: 'Patient reports well-controlled blood pressure at home readings.',
          }],
        }],
        items: [],
      }],
    }],
    immunisations: [{
      _tempId: 'imm-1',
      vaccineName: 'Influenza vaccine',
      snomedCode: '46233009',
      dateGiven: '2023-10-15',
      status: 'completed',
      administeringPractitionerTempId: 'prac-3',
      locationTempId: 'loc-1',
      notes: [],
    }],
    investigations: [{
      _tempId: 'inv-1',
      name: 'Full blood count',
      snomedCode: '26604007',
      date: '2024-01-10',
      performerTempId: 'prac-1',
      results: [{
        _tempId: 'invr-1',
        name: 'Haemoglobin',
        snomedCode: '718-7',
        value: '138',
        unit: 'g/L',
        referenceRangeLow: '120',
        referenceRangeHigh: '160',
        interpretation: 'normal',
      }],
    }],
    referrals: [{
      _tempId: 'ref-1',
      date: '2024-03-01',
      recipientName: 'Cardiology Outpatients',
      priority: 'routine',
      reason: 'Chest pain assessment',
      status: 'active',
      requesterTempId: 'prac-1',
      notes: [],
    }],
    diaryEntries: [{
      _tempId: 'diary-1',
      description: 'Annual diabetes review',
      snomedCode: '390906001',
      date: '2024-06-01',
      occurrenceStart: '2024-06-01',
      clinicianTempId: 'prac-1',
      status: 'active',
      intent: 'plan',
      notes: [],
    }],
    codedData: [{
      _tempId: 'coded-1',
      description: 'Body weight',
      snomedCode: '27113001',
      date: '2024-02-14',
      value: '78',
      unit: 'kg',
      performerTempId: 'prac-3',
    }],
    documents: [{
      _tempId: 'doc-1',
      type: 'Discharge summary',
      date: '2023-11-20',
      description: 'Discharge summary from Leeds General Infirmary',
      status: 'current',
      authorTempId: 'prac-1',
      custodianOrgTempId: 'org-1',
    }],
  }
}
